# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ni8TtH4NLjCQFc1pyoYBV-nwYuhjGbQz
"""

# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDYYD5x-iOBCnLa-4VvWAABwndTH8S5H
"""

from google.colab.patches import cv2_imshow
import cv2

picture1=cv2.imread("1.jpg")
picture2=cv2.imread("2.jpg")
picture3=cv2.imread("3.jpg")

cv2_imshow(picture1)
cv2_imshow(picture2)
cv2_imshow(picture3)


color1=cv2.cvtColor(picture1,cv2.COLOR_BGR2GRAY)
cv2_imshow(color1)
color2=cv2.cvtColor(picture2,cv2.COLOR_BGR2GRAY)
cv2_imshow(color2)
color3=cv2.cvtColor(picture3,cv2.COLOR_BGR2GRAY)
cv2_imshow(color3)